name = "KD232"
uuid = "41458dd0-f39a-4bb6-a4e0-031fda6b0048"
authors = ["nathanrboyer <nathanrobertboyer@gmail.com> and contributors"]
version = "0.1.0"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Weave = "44d3d7a6-8a23-5bf8-98c5-b353f8df5ec9"

[targets]
test = ["Test", "Weave"]
